---
editor_options: 
  chunk_output_type: console
---

# Compare BIOCLIM and model predictions

## Compare BIOCLIM and GAM predictions at random locations

First sample locations.

```{r}
# melt data
sample_locations = 
  sample_locations |>
  pivot_longer(
    cols = !c("x", "y", "ID", "coast", "elev", "lat")
  )

# assign season and climvar
sample_locations = mutate(
  sample_locations,
  season = str_extract(
    name, pattern = "dry|rainy"
  ),
  climvar = str_extract(
    name, pattern = "temp|ppt"
  ),
  climvar = if_else(
    climvar == "temp", "t_mean", "ppt"
  )
)
```

Link with GAM predictions.

```{r}
# remove t_sd
data_pred = filter(
  data_pred,
  climvar != "t_sd"
)

# nest by season and variable
sample_locations = nest(
  sample_locations,
  chelsa = !c("season", "climvar")
)

# link with data predictions
data_pred = left_join(
  data_pred,
  sample_locations
)
```

Get GAM predictions at chelsa sample locations.

```{r}
# sample locations from GAM predictions
data_pred = mutate(
  data_pred,
  chelsa = map2(chelsa, mean_pred, function(ch, pr) {
    ch |>
      rename(
        bioclim_val = "value"
      ) |>
      mutate(
        pred_val = terra::extract(pr, ch[, c("x", "y")]) 
        # the naming doesn't quite work
      )
  })
)

# make copy
data_gam_validate = data_pred |>
  select(season, climvar, forms, chelsa)

# unnest data
data_gam_validate = unnest(
  data_gam_validate,
  cols = chelsa
)

# convert from to characters
data_gam_validate = mutate(
  data_gam_validate,
  forms = as.character(forms)
)

## extract pred val
data_gam_validate = data_gam_validate |>
  mutate(
    pred_val = pred_val$lyr1
  )

# rename and drop some variables
# save data
write_csv(
  data_gam_validate,
  file = "data/output/data_gam_validate_compare.csv"
)
```


```{r}
# use RMSE Measure for 10 chunks of 1000 coordinates
data_gam_validate = group_by(
  data_gam_validate,
  season, climvar, forms
) |>
  mutate(
  group = rep(seq(10), each = 1e3L)
)

# save RMSE measures for plotting --- plot script in figure scripts
data_mae = 
  group_by(
    data_gam_validate,
    season, climvar, forms, group
  ) |>
  summarise(
    mae = mean(
      abs(
        bioclim_val - pred_val
      ), na.rm = TRUE
    )
  )

# save data
write_csv(
  data_mae,
  file = "data/output/data_gam_comparison_mae.csv"
)
```

## Compare BIOCLIM and GAM predictions at survey sites

```{r}
# read survey sites
survey_sites = read_excel(
  "data/raw/2020-resurvey-sites-master.csv.xlsx"
) |>
  rename(
    x = "longitude",
    y = "latitude"
  )

# sample rasters at survey sites
# BIOCLIM samples
survey_sites = mutate(
  survey_sites,
  terra::extract(
    c(chelsa_t_mean, chelsa_ppt_sum),
    survey_sites[, c("x", "y")]
  )
)

# remove id
survey_sites = select(survey_sites, -ID)

# melt data
survey_sites = pivot_longer(
  survey_sites,
  cols = !c("site_code", "x", "y")
) |>
  mutate(
    season = str_extract(
    name, pattern = "dry|rainy"
  ),
  climvar = str_extract(
    name, pattern = "temp|ppt"
  ),
  climvar = if_else(
    climvar == "temp", "t_mean", "ppt"
  )
)
# nest data
survey_sites = nest(
  survey_sites,
  chelsa = !c("season", "climvar")
)

# remove chelsa data
data_pred = select(data_pred, -chelsa)

# link survey data
survey_sites = left_join(
  survey_sites,
  data_pred
)

survey_sites = mutate(
  survey_sites,
  chelsa = map2(chelsa, mean_pred, function(ch, pr) {
    ch |>
      rename(
        bioclim_val = "value"
      ) |>
      mutate(
        pred_val = terra::extract(pr, ch[, c("x", "y")])$lyr1 
        # the naming doesn't quite work
      )
  })
)

survey_sites = survey_sites |>
  select(season, climvar, chelsa, forms) |>
  mutate(
    forms = as.character(forms)
  ) |>
  unnest(
    cols = chelsa
  )

# save measures at survey sites
write_csv(
  survey_sites,
  file = "data/output/data_gam_compare_survey_sites.csv"
)
```