---
editor_options: 
  chunk_output_type: console
---

# Climate trends

```{r}
library(tidyverse)
library(ggplot2)
library(colorspace)
library(patchwork)

library(terra)
library(stars)
```

Load data.

```{r}
lt_clim_data = read_csv("data/output/data_clim_summary.csv")

# filter for study area
lt_clim_summary = lt_clim_data |> 
  filter(
    between(y, 9.5, 12),
    between(x, 76, 78),
    variable != "tmean_std"
  )
```

```{r}
# get elevation
elevation = terra::rast("data/spatial/raster_elevation.tif")
coords = ungroup(lt_clim_summary) |> distinct(x, y)

# extract values
coords$elev = terra::extract(elevation, coords)$alt
# make stars for ggplot
elevation = stars::st_as_stars(elevation)
```

```{r}
# plot site locations
plot_sites = ggplot()+
  geom_stars(
    data = elevation,
    downsample = 2
  )+
  geom_point(
    data = coords,
    aes(x, y),
    size = 2
  )+
  scale_fill_continuous_sequential(
    palette = "Batlow",
    na.value = "transparent",
    limits = c(0, 2650),
    name = "elev"
  )+
  theme_test()+
  theme(
    legend.position = "top",
    legend.key.height = unit(2, "mm"),
    legend.key.width = unit(10, "mm")
  )+
  coord_sf(
    expand = F
  )+
  labs(
    x = "long",
    y = "lat"
  )
```


```{r}
# nest data
lt_clim_summary = 
  lt_clim_summary |> 
  group_by(x, y, variable) |> 
  nest()

# add elevation
lt_clim_summary = left_join(
  lt_clim_summary, coords
)

# split by variable
lt_clim_summary = unnest(lt_clim_summary, cols = "data")
lt_clim_summary = nest(lt_clim_summary, !variable)
```

```{r}
plots = pmap(.l = lt_clim_summary, .f = function(variable, data) {
  ggplot(data)+
    geom_line(
      aes(year, value_mean, col = elev, 
          group = interaction(x, y))
    )+
    scale_colour_continuous_sequential(
      palette = "Batlow",
      na.value = "transparent",
      limits = c(0, 2650),
      name = "elev"
    )+
    scale_x_continuous(
      breaks = c(1870, 1900, 1930, 1960, 1990, 2018)
    )+
    theme_grey()+
    theme(
      strip.placement = "outside",
      axis.text.y = element_text(
        angle = 90, hjust = 0.5
      ),
      panel.border = element_rect(
        colour = 1, fill = NA
      ),
      legend.position = "top",
      legend.key.height = unit(2, "mm"),
      legend.key.width = unit(10, "mm")
    )+
    labs(
      x = "Year",
      y = if_else(
        variable == "ppt_sum",
        "Monthly ppt.",
        "Mean temp."
      )
    )
})

plot_trend = wrap_plots(plots, guides = "collect", ncol = 1) &
  theme(
    legend.position = "top"
  )
```

```{r}
wrap_plots(
  plot_sites,
  plot_trend,
  ncol = 2
) |>
  ggsave(
    filename = "figures/fig_climate_trend.png"
  )
```

